#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $IOT_USER WITH ENCRYPTED PASSWORD '$IOT_PASS';
    CREATE DATABASE $IOT_DB;
    GRANT ALL PRIVILEGES ON DATABASE $IOT_DB TO $IOT_USER;
EOSQL